"""make submission widget_id nullable on delete set null

Revision ID: 4c4a70cbdc97
Revises: a287db74a56b
Create Date: 2026-08-10 14:15:05.097999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4a70cbdc97'
down_revision: Union[str, Sequence[str], None] = 'a287db74a56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'widget_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_submissions_widget_id_widgets'), 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_submissions_widget_id_widgets'), 'submissions', 'widgets', ['widget_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Orphaned submissions are exactly what the upgrade makes possible, and they
    # cannot exist under the restored NOT NULL. Postgres would reject the
    # alter_column below with a constraint violation that says nothing about why.
    # Refuse up front instead, and leave the decision about real data to a human:
    # the alternative is silently deleting submissions during a downgrade.
    orphaned = op.get_bind().execute(
        sa.text("SELECT count(*) FROM submissions WHERE widget_id IS NULL")
    ).scalar_one()
    if orphaned:
        raise RuntimeError(
            f"Cannot downgrade: {orphaned} submission(s) have widget_id IS NULL "
            "and would violate the restored NOT NULL constraint. Reassign or "
            "delete them explicitly, then re-run this downgrade."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_submissions_widget_id_widgets'), 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_submissions_widget_id_widgets'), 'submissions', 'widgets', ['widget_id'], ['id'], ondelete='CASCADE')
    op.alter_column('submissions', 'widget_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
