"""add widget, form_field, submission models with cascade

Revision ID: a287db74a56b
Revises: a7926005cb44
Create Date: 2026-08-10 12:20:45.336078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a287db74a56b'
down_revision: Union[str, Sequence[str], None] = 'a7926005cb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('button_text', sa.String(length=100), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_widgets_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widgets'))
    )
    op.create_index(op.f('ix_widgets_customer_id'), 'widgets', ['customer_id'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], name=op.f('fk_form_fields_widget_id_widgets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_fields'))
    )
    op.create_index(op.f('ix_form_fields_widget_id'), 'form_fields', ['widget_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitter_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('geo_country', sa.String(length=100), nullable=True),
    sa.Column('geo_city', sa.String(length=100), nullable=True),
    sa.Column('geo_provider', sa.String(length=50), nullable=True),
    sa.Column('is_spam', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_submissions_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], name=op.f('fk_submissions_widget_id_widgets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_index(op.f('ix_submissions_customer_id'), 'submissions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_submissions_widget_id'), 'submissions', ['widget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_widget_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_customer_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_form_fields_widget_id'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_widgets_customer_id'), table_name='widgets')
    op.drop_table('widgets')
    # ### end Alembic commands ###
